default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

lane :pod do
  cocoapods(use_bundle_exec: false)
end

lane :tests do
  pod
  run_tests(workspace: "VPlan.xcworkspace",
            devices: ["iPhone 8"],
            scheme: "VPlan")
end

lane :distribution do
     firebase_app_distribution(
              app: "1:842460145206:ios:5ed71eb01f4b09647d1a97",
              groups: "testers",
              ipa_path: "./VPlan.ipa"
         )
end

