default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

lane :pod do
  cocoapods(use_bundle_exec: false)
end

lane :tests do
  pod
  run_tests(workspace: "VPlan.xcworkspace",
            devices: ["iPhone 8"],
            scheme: "VPlan")
end
